version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  commit-message:
    prefix: "deps"
    prefix-development: "chore"
  groups:
    helia-deps: # group all helia/libp2p deps together
      patterns:
        - "*helia*"
        - "*libp2p*"
        - "*multiformats*"
        - "*blockstore*"
        - "*datastore*"
    kubo-deps: # group kubo, kubo-rpc-client, and ipfsd-ctl updates
      patterns:
        - "*kubo*"
        - "ipfsd-ctl"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: chore
